;title='Reboot Menu'

[*Reboot Menu]

[Reboot - Autoboot]
reboot

[Hekate    -    Bootloader]
reboot HEKATE

[Shutdown    -    Power Off]
shutdown


[*Set Autoboot to]
;mode=forwarder
package_source './reboot.ini'