;title='Set Autoboot'

[@]


[Header]
;mode=table
;background=false
;header_indent=true
;gap=17
'Launch'= ''

[Atmosphere     -    Emu/SysMMC]
set-ini-val /bootloader/hekate_ipl.ini config autoboot 1
set-ini-val /bootloader/hekate_ipl.ini config autoboot_list 0

[Safe Mode     -    Emu/SysMMC]
set-ini-val /bootloader/hekate_ipl.ini config autoboot 2
set-ini-val /bootloader/hekate_ipl.ini config autoboot_list 0


[Gap]
;mode=table
;background=false
;gap=20

[Header]
;mode=table
;background=false
;header_indent=true
;gap=17
'More Configs'= ''

[Semi Stock    -    SysMMC]
set-ini-val /bootloader/hekate_ipl.ini config autoboot 1
set-ini-val /bootloader/hekate_ipl.ini config autoboot_list 1

[Semi Safe    -    SysMMC]
set-ini-val /bootloader/hekate_ipl.ini config autoboot 2
set-ini-val /bootloader/hekate_ipl.ini config autoboot_list 1